version: "3.9"
services:
  social_network:
      container_name: social_network
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - postgres
      ports:
      - "${SERVER_PORT}:8080"  

  postgres:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    ports:
        - 8081:8080      

volumes:
  pg-data:

networks:
    default:
        name: social_network
